### ISSUE TITLE
Add security definition options

### ISSUE THREAD

**Issue by zenit1scada** [RemyJeancolas/restify-swagger-jsdoc#13]
Please add support for security definitions, like
`const securityDefinitions = {};
    if (options.securityDefinitions) {
        Object.keys(options.securityDefinitions).forEach(key => {
            securityDefinitions[key] = options.securityDefinitions[key];
        });
    }
    const swaggerSpec = swaggerJSDoc({
        swaggerDefinition: {
            info: {
                title: options.title,
                version: options.version,
                description: typeof options.description === 'string' ? options.description : undefined
            },
            host: typeof options.host === 'string' ? options.host.replace(/\/+$/, '') : undefined,
            basePath: typeof options.routePrefix === 'string' ? `/${options.routePrefix.replace(/^\/+/, '')}` : '/',
            schemes: Array.isArray(options.schemes) ? options.schemes : undefined,
            tags: Array.isArray(options.tags) ? options.tags : [],
            securityDefinitions: securityDefinitions
        },
        apis: Array.isArray(options.apis) ? options.apis : []
    });`

**Comment by RemyJeancolas** [comment]
Never used this, but thanks for the info and the snippet, I'll have a look.
It doesn't seem complicated.

**Comment by cmckni3** [comment]
I would like to add removing the security definitions completely if the object is empty. This will automatically remove the `Authorize` button.

**Comment by RemyJeancolas** [comment]
Implemented in `v3.2.0`, also removed the `Authorize` button when `securityDefinitions` are null or empty as suggested by @cmckni3 .
