### ISSUE TITLE
update to latest UI?

### ISSUE THREAD

**Issue by cmckni3** [RemyJeancolas/restify-swagger-jsdoc#15]
UI served looks like the old UI compared to the UI from the latest docker image.

**Comment by RemyJeancolas** [comment]
Hi @cmckni3, indeed I still use swagger-ui V2, the V3 package uses the latest version of the UI.
I have been thinking of upgrading for a while actually, but didn't find time to do it, I'll try to do it as soon as I can.
In the meantime PRs are welcome :)

**Comment by cmckni3** [comment]
Sure thing. Another PR incoming soon.

**Comment by cmckni3** [comment]
https://github.com/RemyJeancolas/restify-swagger-jsdoc/pull/17

whenever you have a chance @RemyJeancolas

**Comment by cmckni3** [comment]
FWIW, I'm already using it in production.
