### ISSUE TITLE
Support Restify 8?

### ISSUE THREAD

**Issue by DerMika** [RemyJeancolas/restify-swagger-jsdoc#22]
Is there a plan to release a version with support for Restify 8?

**Comment by RemyJeancolas** [comment]
Hello @DerMika, sorry for the late answer but I just tested it with restify 8 and it should work out of the box.
Do you enconter a specific issue ?

**Comment by DerMika** [comment]
No, I haven't tried upgrading yet because this packages requirements start complaining about needing restify 7.x

**Comment by RemyJeancolas** [comment]
Ok so I might just need to update the `peerDependencies` **[here](https://github.com/RemyJeancolas/restify-swagger-jsdoc/blob/master/package.json#L80)** to solve this issue.
I'll give it a shot tomorrow and will let you know.

**Comment by DerMika** [comment]
Okay, thanks a lot!

**Comment by RemyJeancolas** [comment]
Hi @DerMika, I just published a new version (`v3.1.1`) that should remove the warning if you try to use my module with a restify version greater than `v7`, it should fix the issue on your side.
Can you let me know if it's ok for you when you get a chance ?
Thanks by advance :smiley:

**Comment by RemyJeancolas** [comment]
Closing this issue as it should be fixed and received no answer from the requester.
@DerMika feel free to reopen if it's still present.
