### ISSUE TITLE
Major security flaw giving public access to the filesystem of the host.

### ISSUE THREAD

**Issue by xylesoft** [RemyJeancolas/restify-swagger-jsdoc#23]
```javascript
 options.server.get(`${publicPath}/*`, (req, res, next) => {
    const file = req.params['*'];
    fs.readFile(path.resolve(swaggerUiPath, file), (err, content) => {
```
(Assuming publicPath = /docs) 

With the above code in mind, you can provide `http://<host>/docs/../webpack.config.js` and this package will return all the content of that file from https://github.com/swagger-api/swagger-ui/blob/master/webpack.config.js. God forbid if someone is able to workout the path to the root of the operating system.

My suggestion is to use regex instead of a wildcard.

I used `/${publicPath}/:file(^[a-z\-]+\.[js|html|css])` as a fix. This doesn't allow sub-directories nor does it allow `/..`.

**Comment by RemyJeancolas** [comment]
Fixed in [`v3.2.1`](https://github.com/RemyJeancolas/restify-swagger-jsdoc/releases/tag/v3.2.1), thank you very much for reporting this issue :+1: 
Closing this PR, don't hesitate to create another issue if you see anything else, thanks again !
