### ISSUE TITLE
Adding security with basicAuth cause Error on swagger.json validation.

### ISSUE THREAD

**Issue by nithin-ideas2it** [RemyJeancolas/restify-swagger-jsdoc#5]
Hi RemyJeancolas, restify-swagger-jsdoc saved my time a lot.. great. The issue when we add security cause Error on swagger.JSON validation.

ex: on api js file we have

router.js

```
/**
  *@swagger
  *securityDefinitions:
  *  basicAuth:
  *    type: basic
  *security:
  *  - basicAuth: []
  */
```

On swagger.json it results: 
```
"paths": {
	"security": {
		"0": {
			"basicAuth": []
		}
	}

```
It should be 
```
"security": [
    {
      "basicAuth": []
    }
  ]

```
Please help, what we missing here.

**Comment by nithin-ideas2it** [comment]
The above issue with restify-swagger-jsdoc v1.0.8, but in the latest version(v1.1.1) with updated swagger ui authorization is not working.
So, for now, we will revert back to v1.0.8.

Can you help on this?

**Comment by RemyJeancolas** [comment]
Hi @nithin-ideas2it, thanks for reporting the issue.

To be honest I don't use authorization in swagger, so I didn't test this part before switching to swagger-ui V3.
After some research, it seems that swagger-ui V3 is not mature enough to handle authorization properly, so to avoid more issues I just created a new version for restify-swagger-jsdoc (1.1.2) that uses swagger-ui V2, and created a dedicated branch to test swagger-ui v3, when it will be mature enough I'll update the package.

Let me know if the last version of my package fixes your issue.

**Comment by nithin-ideas2it** [comment]
Thank you @RemyJeancolas , the latest version with swagger-ui V2 working fine in my dev system. but I really worried about swagger json validation error when security enable. It is ok. For now, i will close the issue. Please update me. when you are dealing with security option.
